--- 
- name: ping to all servers
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: pinging
      ping:

- name: install apache and start
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: installing
      apt: name=apache2 state=latest
    - name: starting
      service: name=apache2 state=started enabled=yes

